server:
  forward-headers-strategy: framework

spring:
  data.rest.base-path: /datarest
  datasource:
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    #defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: [ ]
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  file:
    name: app/logs/application.log

info:
  app:
    name: hw16-actuator-hateoas

management:
  server:
    port: 8081
  info:
    env:
      enabled: true
    build:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,logfile,loggers,threaddump,env
  endpoint:
    health:
      show-details: always
    logfile:
      enabled: true
      external-file: ${logging.file.name}
    group:
      readiness:
        include: readinessState, db, domain, databaseConnection
      liveness:
        include: livenessState
  metrics:
    tags:
      application: hw16-actuator-hateoas
    distribution:
      percentiles-histogram:
        http.server.requests: true
