services:
  mongo:
    image: mongo:7.0.14
    platform: linux/arm64
    container_name: mongo-local
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: unless-stopped

volumes:
  mongo_data:
