spring:
  h2:
    console:
      enabled: false
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: []
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
