app:
  logging:
    dir: ${LOG_DIR:/app/logs}
    file: ${LOG_FILE:application.log}

server:
  forward-headers-strategy: framework
  port: 8080

spring:
  application:
    name: library-service
  
  data:
    rest:
      base-path: /datarest
      default-media-type: application/hal+json
      return-body-on-create: true
      return-body-on-update: true
      detection-strategy: annotated
  
  datasource:
    url: jdbc:h2:mem:maindb;DB_CLOSE_DELAY=-1
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
    show-sql: false
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
  sql:
    init:
      platform: postgresql
      mode: always
      data-locations: classpath:/data-postgresql.sql
      schema-locations: [ ]
  h2:
    console:
      enabled: false
      path: /h2-console

logging:
  level:
    ru.otus.hw: DEBUG
    org.springframework.data.rest: DEBUG

info:
  app:
    name: hw16-actuator-hateoas

management:
  server:
    port: 8081
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,logfile,loggers,threaddump,httptrace
      base-path: /actuator
    logfile:
      enabled: true
      external-file: ${logging.file.name}
  endpoint:
    health:
      show-details: always
  
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
