global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'library-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'library-service'

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']