server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
  r2dbc:
    url: r2dbc:h2:mem:///maindb
    username: sa
    password:

  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: []

  h2:
    console:
      enabled: false
      path: /h2-console

  thymeleaf:
    reactive:
      max-chunk-size: 8192