spring:
  profiles:
    active: dev

  data:
    mongodb:
      uri: mongodb://localhost:27017/library

  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 50
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  shell:
    interactive:
      enabled: true
  h2:
    console:
      enabled: false
      path: /h2-console
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: [ ]


logging:
  level:
    io.mongock: debug

mongock:
  enabled: true
  runner-type: initializingbean
  migration-scan-package:
    - ru.otus.hw.mongo.migrations