spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

#  profiles:
#    active: dev

  data:
    mongodb:
#      database: library
#      port: 0
      uri: mongodb://localhost:27017/library

  datasource:
    url: jdbc:h2:mem:maindb
    driver-class-name: org.h2.Driver
    username: sa
    password:
    hikari:
      maximum-pool-size: 16
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        jdbc.fetch_size: 1000
        default_batch_fetch_size: 200
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml

  shell:
    interactive:
      enabled: true
    command:
      version:
        enabled: false

  h2:
    console:
      enabled: true
      path: /h2-console
  sql:
    init:
      mode: always
      data-locations: classpath:/data.sql
      schema-locations: [ ]


logging:
  level:
    io.mongock: debug

app:
  batch:
    id-mapping-cache:
      maximum-size: 500000
    thread-pool:
      thread-name-prefix: batch-
      core-pool-size: 4
      max-pool-size: 8
      queue-capacity: 0
    chunk-sizes:
      authors: 2000
      genres: 1000
      books: 10000
      comments: 20000
    progress-listeners:
      authors: 5000
      genres: 200
      books: 10000
      comments: 20000

#de:
#  flapdoodle:
#    mongodb:
#      embedded:
#        version: 7.0.14

mongock:
  enabled: true
  transactional: false
  runner-type: initializingbean
  migration-scan-package:
    - ru.otus.hw.db.mongo.migration
